#!/bin/sh
_hostname=$(hostname)
_version=$(cut -d"'" -f2 < /usr/local/lib/python3.9/dist-packages/pwnagotchi/_version.py)
echo
echo "(◕‿‿◕) $_hostname"
echo
echo "    Hi! I'm a pwnagotchi $_version"
echo
echo "    Config: /etc/pwnagotchi/config.toml"
echo "    Plugin config: /etc/pwnagotchi/conf.d/"
echo "    Config options: /etc/pwnagotchi/default.toml"
echo "    File is receated on every update, so don't edit it."
echo
echo "    oPwnGrid is jayofelony's main API, you can check stats at https://opwngrid.xyz"
echo
echo "    Managed by systemd. Here are some basic commands"
echo "    - pwnlog"
echo "    - sudo pwnagotchi --version"
echo "    - sudo pwnagotchi --check-update"
echo
echo "    Service status:"
echo "    sudo systemctl status pwnagotchi"
echo
echo "    Service restart:"
echo "    pwnkill"
echo
echo "    You learn more about me at https://pwnagotchi.ai/"