name: 'CI Jobs'
on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  Lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8' 

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libdbus-1-dev libdbus-glib-1-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install meson
        python -m pip install dbus-python
        pip install -r requirements.txt

    - name: Lint with Ruff
      run: |
        pip install ruff
        ruff --output-format=github .
    continue-on-error: true

  Test-Unit:
    name: Test - Unit
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.8' 
        - name: Install system dependencies
          run: |
            sudo apt-get update
            sudo apt-get install -y libdbus-1-dev libdbus-glib-1-dev
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            python -m pip install meson
            python -m pip install dbus-python
            pip install -r requirements.txt
        - name: Unit Test
          run: |
            echo "okay"
          #python -m unittest discover -p "test_*.py" -v

 
  Build-32:
    name: Build-32
    runs-on: ubuntu-latest
    needs: [Lint, Test-Unit]
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.8' 
        - name: Install system dependencies
          run: |
            sudo apt-get update
            sudo apt-get install -y libdbus-1-dev libdbus-glib-1-dev
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            python -m pip install meson
            python -m pip install dbus-python
            pip install -r requirements.txt

        - name: Test armv6l - Raspberry Pi Zero W
          uses: pguyot/arm-runner-action@v2.5.2
          with:
              cpu: arm1176
              commands: |
                  echo "ARM TEST - Raspberry Pi Zero W"
                  test `uname -m` = 'armv6l'

  Build-64:
    name: Build-64
    runs-on: ubuntu-latest
    needs: [Lint, Test-Unit]
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.8' 
        - name: Install system dependencies
          run: |
            sudo apt-get update
            sudo apt-get install -y libdbus-1-dev libdbus-glib-1-dev
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            python -m pip install meson
            python -m pip install dbus-python
            pip install -r requirements.txt

        - name: Test 64-bit - Raspberry Pi 02w, 3 and 4
          uses: pguyot/arm-runner-action@HEAD
          with:
            base_image: https://dietpi.com/downloads/images/DietPi_RPi-ARMv8-Bullseye.7z
            cpu: cortex-a53
            commands: |
                echo "ARM TEST - Raspberry Pi Zero W"
                test `uname -m` = 'aarch64'