name: ci-url
on:
  workflow_run:
    workflows: ["Publish"]
    types:
      - completed
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' 
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libdbus-1-dev libdbus-glib-1-dev
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install meson
          python -m pip install dbus-python
          pip install -r requirements.txt

      - name: Download 32-bit base image
        run: |
          wget -O 32base_image.img.xz https://github.com/crs-k/pwnagotchi/releases/download/${{ github.event.workflow_run.head_branch }}/pwnagotchi-rpi-bullseye-${{ github.event.workflow_run.head_branch }}-armhf.img.xz 
      
      - name: Unzip 32-bit base image
        run: |
          xz -d 32base_image.img.xz
          
      - name: Download and unzip 64-bit base image
        run: |
          wget -O 64base_image.img.xz https://github.com/crs-k/pwnagotchi/releases/download/${{ github.event.workflow_run.head_branch }}/pwnagotchi-rpi-bullseye-${{ github.event.workflow_run.head_branch }}-arm64.img.xz

      - name: Unzip 64-bit base image
        run: |
          xz -d 64base_image.img.xz

      - name: Test armv6l - Raspberry Pi Zero W 
        uses: pguyot/arm-runner-action@v2.5.2
        with:
          base_image: /home/runner/work/pwnagotchi/32base_image.img
          cpu: arm1176
          commands: |
              echo "ARM TEST - Raspberry Pi Zero W"
              test `uname -m` = 'armv6l'

      - name: Test 64-bit - Raspberry Pi 02w, 3 and 4
        uses: pguyot/arm-runner-action@v2.5.2
        with:
          base_image: /home/runner/work/pwnagotchi/64base_image.img
          cpu: cortex-a53
          commands: |
              echo "ARM TEST - Raspberry Pi 02w, 3 and 4"
              test `uname -m` = 'aarch64'