name: ci-url
on:
  workflow_run:
    workflows: ["Publish"]
    types:
      - completed
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libdbus-1-dev libdbus-glib-1-dev
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install meson
          python -m pip install dbus-python
          pip install -r requirements.txt

      - name: Test armv6l - Raspberry Pi Zero W 
        uses: pguyot/arm-runner-action@v2.5.2
        with:
          base_image: https://github.com/crs-k/pwnagotchi/releases/download/${{  github.ref_name }}/pwnagotchi-rpi-bullseye-${{  github.ref_name }}-arm64.img.xz
          cpu: arm1176
          commands: |
              echo "ARM TEST - Raspberry Pi Zero W"
              test `uname -m` = 'armv6l'

      - name: Test 64-bit - Raspberry Pi 02w, 3 and 4
        uses: pguyot/arm-runner-action@v2.5.2
        with:
          base_image: https://github.com/crs-k/pwnagotchi/releases/download/${{  github.ref_name }}/pwnagotchi-rpi-bullseye-${{  github.ref_name }}-arm64.img.xz
          cpu: cortex-a53
          commands: |
              echo "ARM TEST - Raspberry Pi 02w, 3 and 4"
              test `uname -m` = 'aarch64'
