name: ci-url
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pguyot/arm-runner-action@v2.5.2
      with:
        base_image: https://github.com/crs-k/pwnagotchi/releases/download/0.3.0/pwnagotchi-v0.3.0.7z
        cpu: arm1176
        commands: |
          sudo python ./setup.py