name: ci-url
on:
  release:
    types: [published]
jobs:
  Lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8' 
    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libdbus-1-dev libdbus-glib-1-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install meson
        python -m pip install dbus-python
        pip install -r requirements.txt

    - name: Lint with Ruff
      run: |
        pip install ruff
        ruff --output-format=github .
      continue-on-error: true

  Test-Unit:
    name: Test - Unit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8' 
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libdbus-1-dev libdbus-glib-1-dev
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install meson
          python -m pip install dbus-python
          pip install -r requirements.txt
      - name: Unit Test
        run: |
          python -m unittest discover -p "test_*.py" -v


  Build:
    name: Build
    runs-on: ubuntu-latest
    needs: [Lint, Test-Unit]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8' 
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libdbus-1-dev libdbus-glib-1-dev
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install meson
          python -m pip install dbus-python
          pip install -r requirements.txt
      - name: ARM build test    
        uses: pguyot/arm-runner-action@v2.5.2
        with:
          base_image: https://github.com/crs-k/pwnagotchi/releases/download/${{ github.event.release.tag_name }}/pwnagotchi-v${{ github.event.release.tag_name }}.7z
          cpu: arm1176
          commands: |
            echo "ARM TEST"
