name: ci-url
on:
  workflow_run:
    workflows: ["Publish"]
    types:
      - completed
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' 

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: env-var
      
      - name: Load environment variable
        run: echo "TAG=$(cat env_var.txt)" >> $GITHUB_ENV
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libdbus-1-dev libdbus-glib-1-dev
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install meson
          python -m pip install dbus-python
          pip install -r requirements.txt

      - name: Download 32-bit base image
        run: |
          wget https://github.com/crs-k/pwnagotchi/releases/download/$TAG/pwnagotchi-rpi-bullseye-$TAG-armhf.img.xz 
          RESULT=$(find . -name "pwnagotchi-rpi-bullseye-$TAG-armhf.img.xz ")
          echo "32bit=$RESULT" >> $GITHUB_ENV

      - name: Download and unzip 64-bit base image
        run: |
          wget https://github.com/crs-k/pwnagotchi/releases/download/$TAG/pwnagotchi-rpi-bullseye-$TAG-arm64.img.xz
          RESULT2=$(find . -name "pwnagotchi-rpi-bullseye-$TAG-armhf.img.xz ")
          echo "64bit=$RESULT2" >> $GITHUB_ENV

      - name: Test armv6l - Raspberry Pi Zero W 
        uses: pguyot/arm-runner-action@v2.5.2
        with:
          base_image: file://$32bit
          commands: |
            echo "ARM TEST - Raspberry Pi Zero W"
            test `uname -m` = 'armv6l'

      - name: Test 64-bit - Raspberry Pi 02w, 3 and 4
        uses: pguyot/arm-runner-action@v2.5.2
        with:
          base_image: file://$64bit
          commands: |
              echo "ARM TEST - Raspberry Pi 02w, 3 and 4"
              test `uname -m` = 'aarch64'