name: Test armv6l cpu option
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
    - name: Test armv6l cpu option
      uses: pguyot/arm-runner-action@v2.5.2
      with:
        cpu: arm1176
        commands: |
            pip install -r requirements.txt
            python3 setup.py